# -*- coding: utf-8 -*-
"""train_diagram_architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb6UAt39mUbv7gp0RD6KHyvWXe8aFBG2
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np

ML_DATASET_DIR = "/home/ahad/Documents/fyp_pipeline_outputs/fyp_processed_dataset"
INDEX_PATH = os.path.join(ML_DATASET_DIR, "master_dataset_index.csv")

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Custom Diagram Architecture Target Device: {device.type.upper()}")

class UrduSignLanguageDataset(Dataset):
    def __init__(self, index_file_path, split_type='train'):
        self.df_master = pd.read_csv(index_file_path)
        self.df_split = self.df_master[self.df_master['split'] == split_type].reset_index(drop=True)

    def __len__(self):
        return len(self.df_split)

    def __getitem__(self, idx):
        row = self.df_split.iloc[idx]
        matrix_path = row['landmark_output_path']
        landmarks_sequence = np.load(matrix_path, allow_pickle=True).astype(np.float32)
        label = int(row['label_idx'])
        return torch.tensor(landmarks_sequence), torch.tensor(label, dtype=torch.long)

class JointAttention(nn.Module):
    def __init__(self, d_model):
        super(JointAttention, self).__init__()
        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(d_model, d_model)
        self.v_proj = nn.Linear(d_model, d_model)
        self.out_proj = nn.Linear(d_model, d_model)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x):
        Q = self.q_proj(x)
        K = self.k_proj(x)
        V = self.v_proj(x)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / np.sqrt(x.size(-1))
        attn_weights = self.softmax(scores)

        context = torch.matmul(attn_weights, V)
        output = self.out_proj(context) + V
        return self.softmax(output)

class CustomDiagramTransformer(nn.Module):
    def __init__(self, num_classes=20, input_dim=144, hidden_dim=256, num_heads=4, num_layers=2):
        super(CustomDiagramTransformer, self).__init__()

        self.input_projection = nn.Linear(input_dim, hidden_dim)

        self.main_block = nn.Sequential(
            nn.Conv1d(in_channels=hidden_dim, out_channels=hidden_dim, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.BatchNorm1d(hidden_dim),
            nn.Dropout(0.1)
        )
        self.auxiliary_block = nn.Sequential(
            nn.Conv1d(in_channels=hidden_dim, out_channels=hidden_dim, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.BatchNorm1d(hidden_dim),
            nn.Dropout(0.1),
            nn.MaxPool1d(kernel_size=2)
        )

        self.joint_attention = JointAttention(hidden_dim)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim, nhead=num_heads, dim_feedforward=hidden_dim * 2, dropout=0.3, batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        self.classifier_head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        x = self.input_projection(x)

        x = x.permute(0, 2, 1)
        x = self.main_block(x)
        x = self.auxiliary_block(x)

        x = x.permute(0, 2, 1)

        x = self.joint_attention(x)

        x = self.transformer_encoder(x)

        x = torch.mean(x, dim=1)
        return self.classifier_head(x)

BATCH_SIZE = 64
train_dataset = UrduSignLanguageDataset(INDEX_PATH, split_type='train')
val_dataset = UrduSignLanguageDataset(INDEX_PATH, split_type='val')

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

model = CustomDiagramTransformer(num_classes=20).to(device)

EPOCHS = 120
INITIAL_LR = 0.001
STRICT_WD = 0.005

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=INITIAL_LR, weight_decay=STRICT_WD)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)

best_val_loss = float('inf')
weights_save_path = os.path.join(ML_DATASET_DIR, 'diagram_transformer_model.pth')

print(f"Launching Custom Diagram Architecture Pipeline for {EPOCHS} Epochs...")

for epoch in range(EPOCHS):
    model.train()
    running_loss, correct_train, total_train = 0.0, 0, 0
    for batch_X, batch_y in train_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)

        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total_train += batch_y.size(0)
        correct_train += (predicted == batch_y).sum().item()

    epoch_train_loss = running_loss / total_train
    epoch_train_acc = (correct_train / total_train) * 100

    model.eval()
    running_val_loss, correct_val, total_val = 0.0, 0, 0
    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)

            running_val_loss += loss.item() * batch_X.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total_val += batch_y.size(0)
            correct_val += (predicted == batch_y).sum().item()

    epoch_val_loss = running_val_loss / total_val
    epoch_val_acc = (correct_val / total_val) * 100

    scheduler.step()

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save(model.state_dict(), weights_save_path)
        chk = "star"
    else:
        chk = ""

    if (epoch + 1) % 10 == 0 or epoch == 0 or "star" in chk:
        print(f"Epoch [{epoch+1}/{EPOCHS}] Train Loss: {epoch_train_loss:.4f} Acc: {epoch_train_acc:.2f}% | Val Loss: {epoch_val_loss:.4f} Acc: {epoch_val_acc:.2f}% {chk}")

print(f"\nCustom Diagram Architecture Complete! Saved to: {weights_save_path}")
