# -*- coding: utf-8 -*-
"""train_transformer_ultra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb6UAt39mUbv7gp0RD6KHyvWXe8aFBG2
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ML_DATASET_DIR = "/home/ahad/Documents/fyp_pipeline_outputs/fyp_processed_dataset"
INDEX_PATH = os.path.join(ML_DATASET_DIR, "master_dataset_index.csv")

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Execution Target Device: {device.type.upper()}")

class UrduSignLanguageDataset(Dataset):
    def __init__(self, index_file_path, split_type='train'):
        self.df_master = pd.read_csv(index_file_path)
        self.df_split = self.df_master[self.df_master['split'] == split_type].reset_index(drop=True)

    def __len__(self):
        return len(self.df_split)

    def __getitem__(self, idx):
        row = self.df_split.iloc[idx]
        matrix_path = row['landmark_output_path']
        landmarks_sequence = np.load(matrix_path, allow_pickle=True).astype(np.float32)
        label = int(row['label_idx'])
        return torch.tensor(landmarks_sequence), torch.tensor(label, dtype=torch.long)

class SignLanguageTransformer(nn.Module):
    def __init__(self, num_classes=20, input_dim=144, num_heads=4, num_layers=2, hidden_dim=256, dropout=0.5):
        super(SignLanguageTransformer, self).__init__()
        self.input_projection = nn.Linear(input_dim, hidden_dim)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim, nhead=num_heads, dim_feedforward=hidden_dim * 2, dropout=dropout, batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc_classifier = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = self.input_projection(x)
        x = self.transformer_encoder(x)
        x = torch.mean(x, dim=1)
        return self.fc_classifier(x)

BATCH_SIZE = 64
print(f"Building optimized PyTorch DataLoaders (Batch Size: {BATCH_SIZE})...")

train_dataset = UrduSignLanguageDataset(INDEX_PATH, split_type='train')
val_dataset = UrduSignLanguageDataset(INDEX_PATH, split_type='val')

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

model = SignLanguageTransformer(num_classes=20, dropout=0.5).to(device)

EPOCHS = 120
INITIAL_LR = 0.001
STRICT_WD = 0.005

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=INITIAL_LR, weight_decay=STRICT_WD)

scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)

history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': [], 'lr': []}
best_val_loss = float('inf')
best_epoch = 0

weights_save_path = os.path.join(ML_DATASET_DIR, 'ultra_stricthp_transformer.pth')
plot_save_path = os.path.join(ML_DATASET_DIR, 'ultra_performance_curves.png')

print(f"Launching Strict Optimization Loop for {EPOCHS} Epochs across 20 sentences...")

for epoch in range(EPOCHS):
    current_lr = optimizer.param_groups[0]['lr']
    history['lr'].append(current_lr)

    model.train()
    running_loss, correct_train, total_train = 0.0, 0, 0
    for batch_X, batch_y in train_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)

        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total_train += batch_y.size(0)
        correct_train += (predicted == batch_y).sum().item()

    epoch_train_loss = running_loss / total_train
    epoch_train_acc = (correct_train / total_train) * 100

    model.eval()
    running_val_loss, correct_val, total_val = 0.0, 0, 0
    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)

            running_val_loss += loss.item() * batch_X.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total_val += batch_y.size(0)
            correct_val += (predicted == batch_y).sum().item()

    epoch_val_loss = running_val_loss / total_val
    epoch_val_acc = (correct_val / total_val) * 100

    scheduler.step()

    history['train_loss'].append(epoch_train_loss)
    history['train_acc'].append(epoch_train_acc)
    history['val_loss'].append(epoch_val_loss)
    history['val_acc'].append(epoch_val_acc)

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        best_epoch = epoch + 1
        torch.save(model.state_dict(), weights_save_path)
        checkpoint_msg = f"star (Optimal Weights Checked & Saved! LR: {current_lr:.6f})"
    else:
        checkpoint_msg = f"(LR: {current_lr:.6f})"

    if (epoch + 1) % 5 == 0 or epoch == 0 or "star" in checkpoint_msg:
        print(f"Epoch [{epoch+1}/{EPOCHS}] Train Loss: {epoch_train_loss:.4f} Acc: {epoch_train_acc:.2f}% | Val Loss: {epoch_val_loss:.4f} Acc: {epoch_val_acc:.2f}% {checkpoint_msg}")

print(f"\nDeep Optimization Engine Cycle Complete!")
print(f"Best Validation metrics reached at Epoch {best_epoch} with minimal Loss: {best_val_loss:.4f}")
print(f"Saved Model Weights: {weights_save_path}")

plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 1)
plt.plot(range(1, EPOCHS+1), history['train_acc'], label='Train Acc', color='royalblue')
plt.plot(range(1, EPOCHS+1), history['val_acc'], label='Val Acc', color='darkorange')
plt.axvline(x=best_epoch, color='magenta', linestyle='--', label='Best Model Checkpoint')
plt.title('Strict Learning Accuracy Curves')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(range(1, EPOCHS+1), history['train_loss'], label='Train Loss', color='royalblue', linestyle=':')
plt.plot(range(1, EPOCHS+1), history['val_loss'], label='Val Loss', color='darkorange', linestyle=':')
plt.axvline(x=best_epoch, color='magenta', linestyle='--', label='Best Model Checkpoint')
plt.title('Smooth Cosine Loss Convergence Trend')
plt.xlabel('Epochs')
plt.ylabel('Loss Value')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.savefig(plot_save_path, dpi=300)
print(f"Deep performance graph graphics written to:\n   └─> {plot_save_path}")
