# -*- coding: utf-8 -*-
"""train_baseline_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb6UAt39mUbv7gp0RD6KHyvWXe8aFBG2
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np

ML_DATASET_DIR = "/home/ahad/Documents/fyp_pipeline_outputs/fyp_processed_dataset"
INDEX_PATH = os.path.join(ML_DATASET_DIR, "master_dataset_index.csv")

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"LSTM Training Target Device: {device.type.upper()}")

class UrduSignLanguageDataset(Dataset):
    def __init__(self, index_file_path, split_type='train'):
        self.df_master = pd.read_csv(index_file_path)
        self.df_split = self.df_master[self.df_master['split'] == split_type].reset_index(drop=True)

    def __len__(self):
        return len(self.df_split)

    def __getitem__(self, idx):
        row = self.df_split.iloc[idx]
        matrix_path = row['landmark_output_path']
        landmarks_sequence = np.load(matrix_path, allow_pickle=True).astype(np.float32)
        label = int(row['label_idx'])
        return torch.tensor(landmarks_sequence), torch.tensor(label, dtype=torch.long)

class SignLanguageLSTM(nn.Module):
    def __init__(self, num_classes=20, input_dim=144, hidden_dim=256, num_layers=2, dropout=0.5):
        super(SignLanguageLSTM, self).__init__()
        self.lstm = nn.LSTM(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0
        )
        self.fc_classifier = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        out, (hn, cn) = self.lstm(x)
        out = out[:, -1, :]
        return self.fc_classifier(out)

BATCH_SIZE = 64
train_dataset = UrduSignLanguageDataset(INDEX_PATH, split_type='train')
val_dataset = UrduSignLanguageDataset(INDEX_PATH, split_type='val')

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

model = SignLanguageLSTM(num_classes=20).to(device)

EPOCHS = 120
INITIAL_LR = 0.001
STRICT_WD = 0.005

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=INITIAL_LR, weight_decay=STRICT_WD)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)

best_val_loss = float('inf')
weights_save_path = os.path.join(ML_DATASET_DIR, 'baseline_lstm_model.pth')

print(f"Training Recurrent Baseline LSTM for {EPOCHS} Epochs...")

for epoch in range(EPOCHS):
    model.train()
    running_loss, correct_train, total_train = 0.0, 0, 0
    for batch_X, batch_y in train_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)

        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total_train += batch_y.size(0)
        correct_train += (predicted == batch_y).sum().item()

    epoch_train_loss = running_loss / total_train
    epoch_train_acc = (correct_train / total_train) * 100

    model.eval()
    running_val_loss, correct_val, total_val = 0.0, 0, 0
    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)

            running_val_loss += loss.item() * batch_X.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total_val += batch_y.size(0)
            correct_val += (predicted == batch_y).sum().item()

    epoch_val_loss = running_val_loss / total_val
    epoch_val_acc = (correct_val / total_val) * 100

    scheduler.step()

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save(model.state_dict(), weights_save_path)
        chk = "star"
    else:
        chk = ""

    if (epoch + 1) % 10 == 0 or epoch == 0 or "star" in chk:
        print(f"Epoch [{epoch+1}/{EPOCHS}] Train Loss: {epoch_train_loss:.4f} Acc: {epoch_train_acc:.2f}% | Val Loss: {epoch_val_loss:.4f} Acc: {epoch_val_acc:.2f}% {chk}")

print(f"\nLSTM Training Complete! Best Weights Saved to: {weights_save_path}")
